name = "lean-db"
version = "0.1.0"
defaultTargets = ["lean-db"]

[[lean_lib]]
name = "LeanDB"

[[lean_exe]]
name = "lean-db"
root = "Main"

[[require]]
name = "lean-fmt"
git = "https://github.com/jcreinhold/lean-fmt"
rev = "v4.34.0-rc2"